name: Selenium POM project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install nuget packeges
        run: dotnet restore SeleniumBasicExercise.sln

      - name: Build the test project
        run: dotnet build SeleniumBasicExercise.sln

      - name: run TestProject1
        run: dotnet test TestProject1/TestProject1.csproj

      - name: run TestProject2
        run: dotnet test TestProject2/TestProject2.csproj

      - name: run TestProject3
        run: dotnet test TestProject3/TestProject3.csproj        